export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';


export const GET_SHOP_LOADING = 'GET_SHOP_LOADING';
export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOP_FAIL = 'GET_SHOP_FAIL';

export const GET_NEARBY_LOADING = 'GET_NEARBY_LOADING';
export const GET_NEARBY_SUCCESS = 'GET_NEARBY_SUCCESS';
export const GET_NEARBY_FAIL = 'GET_NEARBY_FAIL';

export const GET_BARBER_LOADING = 'GET_BARBER_LOADING';
export const GET_BARBER_SUCCESS = 'GET_BARBER_SUCCESS';
export const GET_BARBER_FAIL = 'GET_BARBER_FAIL';

export const GET_SERVICES_LOADING = 'GET_SERVICES_LOADING';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAIL = 'GET_SERVICES_FAIL';

export const GET_TIMES_LOADING = 'GET_TIMES_LOADING';
export const GET_TIMES_SUCCESS = 'GET_TIMES_SUCCESS';
export const GET_TIMES_FAIL = 'GET_TIMES_FAIL';

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ADD_CART = 'ADD_CART' ;
export const DELETE_CART = 'DELETE_CART';

export const SEND_PAYMENT_LOADING = 'SEND_PAYMENT_LOADING';
export const SEND_PAYMENT_SUCCESS = 'SEND_PAYMENT_SUCCESS';
export const SEND_PAYMENT_FAIL = 'SEND_PAYMENT_FAIL';

export const ADD_BOOKING_LOADING = 'ADD_BOOKING_LOADING';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
export const ADD_BOOKING_FAIL = 'ADD_BOOKING_FAIL';


export const GET_INVOICE_LOADING = 'GET_INVOICE_LOADING';
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_FAIL = 'GET_INVOICE_FAIL';


export const SET_RATING_LOADING = 'SET_RATING_LOADING';
export const SET_RATING_SUCCESS = 'SET_RATING_SUCCESS';
export const SET_RATING_FAIL = 'SET_RATING_FAIL';

export const SET_DONE_LOADING = 'SET_DONE_LOADING';
export const SET_DONE_SUCCESS = 'SET_DONE_SUCCESS';
export const SET_DONE_FAIL = 'SET_DONE_FAIL';


export const NEW_SERVICE_LOADING = 'NEW_SERVICE_LOADING';
export const NEW_SERVICE_SUCCESS = 'NEW_SERVICE_SUCCESS';
export const NEW_SERVICE_FAIL = 'NEW_SERVICE_FAIL';

export const DELETE_SERVICE_LOADING = 'DELETE_SERVICE_LOADING';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL';

export const UPDATE_SERVICE_LOADING = 'UPDATE_SERVICE_LOADING';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAIL = 'UPDATE_SERVICE_FAIL';



export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';


export const GET_REVIEWS_LOADING = 'GET_REVIEWS_LOADING';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL';


export const GET_PAYMENT_LOADING = 'GET_PAYMENT_LOADING';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL';

